### ISSUE TITLE
Implement velocity dealiasing

### ISSUE THREAD

**Issue by SteepAtticStairs** [netbymatt/nexrad-level-2-data#3]
Would it be even feasible to implement velocity dealiasing for the decoded Level 2 data? It looks like the nyquist velocity is contained in Message 31: https://github.com/netbymatt/nexrad-level-2-data/blob/main/src/classes/Level2Record-31.js#L190

NASA’s [TRMM Radar Software Library](https://github.com/adokter/rsl) allows for dealiasing, if this is helpful for reference at all.

**Comment by netbymatt** [comment]
I looked at PyArt's documentation and it's fairly involved, using graphical filters that they provide within their software. https://arm-doe.github.io/pyart/notebooks/dealiasing_velocity.html

Because it is so involved I feel like it's well outside of the scope of this repo which aims to parse the data within a radar archive file. A new package to handle just this would seem like a better way to go about it. The structured and well organized data coming out of this package should be easy to pass to another tool.
